name: Pulls Cypress Container 

on:
  push:
    branches: [ container-build ]
  pull_request:
    branches: [ container-build ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v1
        
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            natep18f/container-cypress-test
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=false
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          platform: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          
      - name: Security scan
        uses: anchore/scan-action@v3
        with:
          image-reference: "ubuntu:latest"
          fail-build: true
